# ArgoCD Applications for Ride Booking Platform
# These applications will manage services already deployed
# Using local filesystem path (for development/testing)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: gitops
    repoURL: https://github.com/argoproj/argocd-example-apps.git  # Dummy repo - we'll use local sync
    targetRevision: HEAD
    directory:
      include: user-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: driver-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: gitops
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    directory:
      include: driver-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ride-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: gitops
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    directory:
      include: ride-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: gitops
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    directory:
      include: payment-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


