apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ranjan5567/ride-booking-platform.git
    targetRevision: main
    path: gitops
    directory:
      include: user-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: driver-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ranjan5567/ride-booking-platform.git
    targetRevision: main
    path: gitops
    directory:
      include: driver-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ride-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ranjan5567/ride-booking-platform.git
    targetRevision: main
    path: gitops
    directory:
      include: ride-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ranjan5567/ride-booking-platform.git
    targetRevision: main
    path: gitops
    directory:
      include: payment-service-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
